import type { RecordingClip } from './recorder'
import type { SoundId } from '../types/api'

/**
 * Sound Journey API client.
 *
 * Mirrors app/routers/journey.py. Two things are worth knowing about the
 * shapes below:
 *
 *  - `analysis` and `decision` are separate fields. The analysis is what the
 *    microphone measured; the decision is what the progression did about it.
 *    They are kept apart so the UI can show that the second follows from the
 *    first, rather than presenting a verdict with no visible cause.
 *  - Nothing here carries a score generated by a language model. Practice
 *    material comes from `requestMaterial`, performance comes from
 *    `submitJourneyAttempt`, and the two never mix.
 */

export type JourneyAction = 'advance' | 'retreat' | 'hold' | 'hint'
export type JourneyOutcome = 'pass' | 'close' | 'fail' | 'unclear'

/* ── Languages ────────────────────────────────────────────────────────
 *
 * Mirrors api/app/languages.py.
 *
 * A learner's first language personalizes the interface, the bridge shown
 * beside a sound, and the context given to the exercise generator. It is not
 * an input to the acoustic measurement — the same recording scores the same
 * whoever made it — which is both what keeps the pipeline stable and the
 * only honest option, since the reference data is English.
 */

export interface LanguageInfo {
  code: string
  /** English name, for interface copy. */
  name: string
  /** The language's own name in its own script, e.g. "বাংলা". */
  native_name: string
  script: string
  /** False when PhonoPlay has no acoustic reference data for it. */
  can_be_target: boolean
  can_be_native: boolean
  /** Why it cannot be a target. Shown at the point of choosing. */
  target_note: string | null
}

export interface BridgeStep {
  text: string
  kind: 'native' | 'target' | 'word'
  ipa: string | null
  note: string | null
}

/**
 * A familiar starting point for one sound.
 *
 * `anchor_note` describes an articulatory relationship between two sounds —
 * where the tongue goes for each. It is never a claim about what a speaker of
 * a language does or will do.
 */
export interface LanguageBridge {
  native: string
  target_sound: SoundId
  /** Null when the first language is also the target language. */
  anchor: string | null
  anchor_ipa: string | null
  anchor_note: string | null
  progression: string[]
  steps: BridgeStep[]
}

export interface LanguageContext {
  native: LanguageInfo
  target: LanguageInfo
  /** True when the first language differs from the target language. */
  cross_language: boolean
  /** Present on per-sound views. Null when no bridge exists for the pair. */
  bridge?: LanguageBridge | null
}

export interface JourneyStage {
  index: number
  key: string
  band: string
  band_label: string
  /** 0–4. Which of the five visible dots is lit. */
  band_index: number
  title: string
  instruction: string
  material: string
  expected_duration_s: number
  is_first: boolean
  is_last: boolean
}

export interface JourneyBand {
  band: string
  label: string
  index: number
  stages: number[]
}

export interface JourneyState {
  learner_id: string
  sound: SoundId
  language: LanguageContext
  stage: JourneyStage
  bands: JourneyBand[]
  started_at: string
  updated_at: string
  counts: Partial<Record<JourneyOutcome, number>>
  stage_outcomes: JourneyOutcome[]
  history?: JourneyAttemptRecord[]
}

export interface JourneyAttemptRecord {
  id: number
  stage: number
  outcome: JourneyOutcome
  similarity: number | null
  confidence: number | null
  estimated_match: string | null
  feedback_code: string | null
  prompt_text: string | null
  decision: string | null
  created_at: string
}

export interface StageMaterialItem {
  text: string
  display: string | null
  contrast: string | null
  cue: string
}

export interface StageMaterial {
  sound: SoundId
  stage: number
  stage_key: string
  item: StageMaterialItem
  /** "llm" or "fallback". Shown to the learner — never hidden. */
  source: 'llm' | 'fallback'
  position: string
  first_occurrence_only: boolean
  /** What this material was personalized for. The target is always English. */
  native_language: string
  target_language: string
}

export interface JourneyDecision {
  action: JourneyAction
  from_stage: number
  to_stage: number
  reason: string
  vary_material: boolean
  show_hint: boolean
  hint: string | null
}

/** Stage 2 result. Mirrors PronunciationResponse in api/app/schemas.py. */
export interface PronunciationAnalysis {
  target_phoneme: string
  target_ipa: string
  estimated_match: string | null
  estimated_match_ipa: string | null
  similarity_score: number
  confidence: number
  acoustic_features: Record<string, number>
  feedback_code: string
  /** Fixed on every failure, so a failure can never read as a low score. */
  message: string
  /** The specific reason behind a failure headline. */
  detail: string | null
  cue: string | null
  hint: string | null
  assessed: boolean
  candidates: {
    phoneme: string
    ipa: string
    similarity: number
    posterior: number
    features_used: number
    z_scores: Record<string, number>
  }[]
  segment: {
    start_s: number
    end_s: number
    duration_s: number
    salience: number
    method: string
    position_hint: string
  } | null
  quality: {
    duration_s: number
    speech_duration_s: number
    snr_db: number
    clipped_fraction: number
    voiced_fraction: number
    dynamic_range_db: number
    speech_present: boolean
    ok: boolean
    factor: number
    warnings: string[]
    blocking_code: string | null
  }
  speaker: Record<string, number>
  mfcc: number[]
  reference: Record<string, unknown>
  processing_ms: number
  stage: string
}

export interface JourneyAttemptResult {
  analysis: PronunciationAnalysis
  outcome: JourneyOutcome
  decision: JourneyDecision
  journey: JourneyState
  attempt_id: number
}

const LEARNER_KEY = 'phonoplay.learner'

/**
 * A stable, anonymous id for this browser.
 *
 * Not an account and not personal data — it exists so that closing the tab
 * does not erase a journey. Private browsing or cleared site data starts a
 * new one, which is the correct behaviour rather than a bug: there is
 * nothing to recover and nothing was lost that the learner did not choose to
 * discard.
 */
export function learnerId(): string {
  try {
    const existing = localStorage.getItem(LEARNER_KEY)
    if (existing) return existing
    const created =
      typeof crypto !== 'undefined' && 'randomUUID' in crypto
        ? crypto.randomUUID()
        : `learner-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 10)}`
    localStorage.setItem(LEARNER_KEY, created)
    return created
  } catch {
    // Storage can throw outright, not just return null — Safari in private
    // mode, and any browser with site data blocked. A session-only id keeps
    // the journey working for as long as the tab is open.
    return `ephemeral-${Math.random().toString(36).slice(2, 10)}`
  }
}

export class JourneyError extends Error {
  // Declared and assigned separately: `erasableSyntaxOnly` in tsconfig
  // disallows constructor parameter properties, since they emit code rather
  // than erasing to nothing.
  code: string
  retryable: boolean

  constructor(message: string, code: string, retryable: boolean) {
    super(message)
    this.name = 'JourneyError'
    this.code = code
    this.retryable = retryable
  }
}

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  let response: Response
  try {
    response = await fetch(path, init)
  } catch {
    throw new JourneyError(
      'Could not reach the practice service. Check your connection and try again.',
      'NETWORK_UNAVAILABLE',
      true,
    )
  }

  if (!response.ok) {
    let code = 'UNKNOWN'
    let message = 'Something went wrong.'
    let retryable = response.status >= 500
    try {
      const body = await response.json()
      if (body?.error) {
        code = body.error.code ?? code
        message = body.error.message ?? message
        retryable = Boolean(body.error.retryable)
      } else if (body?.detail) {
        message = String(body.detail)
      }
    } catch {
      // A non-JSON error body is still an error; the defaults above stand.
    }
    throw new JourneyError(message, code, retryable)
  }

  return (await response.json()) as T
}

export function fetchStageDefinitions(): Promise<{
  stages: JourneyStage[]
  bands: JourneyBand[]
}> {
  return request('/api/journey/stages')
}

export function fetchJourney(sound: SoundId, learner = learnerId()): Promise<JourneyState> {
  return request(`/api/journey/${encodeURIComponent(learner)}/${sound}`)
}

export function fetchAllJourneys(learner = learnerId()): Promise<{
  learner_id: string
  bands: JourneyBand[]
  journeys: {
    sound: SoundId
    stage: JourneyStage
    started: boolean
    updated_at: string | null
    counts: Partial<Record<JourneyOutcome, number>>
  }[]
}> {
  return request(`/api/journey/${encodeURIComponent(learner)}`)
}

export function fetchLanguages(): Promise<{
  native: LanguageInfo[]
  target: LanguageInfo[]
  default_native: string
  note: string
}> {
  return request('/api/journey/languages')
}

export function fetchProfile(
  learner = learnerId(),
): Promise<{ learner_id: string; language: LanguageContext }> {
  return request(`/api/journey/${encodeURIComponent(learner)}/profile`)
}

/**
 * Set the learner's first language.
 *
 * The server normalises an unrecognised code to English rather than
 * rejecting it, and reports both what was asked for and what was applied, so
 * a stale client loses personalization instead of losing the app.
 */
export function setNativeLanguage(
  code: string,
  learner = learnerId(),
): Promise<{ language: LanguageContext; applied: string; requested: string }> {
  return request(`/api/journey/${encodeURIComponent(learner)}/profile`, {
    method: 'PUT',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ native_language: code }),
  })
}

export function requestMaterial(
  sound: SoundId,
  options: { avoid?: string | null; learner?: string } = {},
): Promise<{ material: StageMaterial; stage: JourneyStage; language: LanguageContext }> {
  const learner = options.learner ?? learnerId()
  return request(`/api/journey/${encodeURIComponent(learner)}/${sound}/material`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ avoid: options.avoid ?? null }),
  })
}

export function submitJourneyAttempt(
  sound: SoundId,
  clip: RecordingClip,
  promptText: string,
  learner = learnerId(),
): Promise<JourneyAttemptResult> {
  const form = new FormData()
  // Audio is only ever sent after the learner explicitly chooses to submit a
  // recording they have had the chance to play back.
  form.append('audio', clip.blob, `attempt.${clip.extension}`)
  form.append('prompt_text', promptText)

  return request(`/api/journey/${encodeURIComponent(learner)}/${sound}/attempt`, {
    method: 'POST',
    body: form,
  })
}
