import { RECENT_SCORES_KEPT, STAGE_ORDER, db, newId, now } from './schema.ts'
import type { Phoneme, PhonemeProfile, SkillType, Trend } from './schema.ts'
import { assessMastery, assessStage, policyFor } from './policy.ts'
import type { LearnerPolicy, MasteryVerdict, StageVerdict } from './policy.ts'
import { getLearningMode } from './settings.ts'

/**
 * Phoneme profiles — the learner model.
 *
 * This is the half of "your pronunciation writes your syllabus" that does the
 * writing. Everything here is derived from acoustic measurements: the
 * similarity the analyser produced, the confidence it had in that reading,
 * and whether it was willing to score the recording at all.
 *
 * **Nothing generated by a language model reaches these numbers.** The model
 * writes practice text; the microphone decides how it went. Keeping that
 * boundary is why `recordMeasurement()` takes a measurement and not, say, an
 * exercise result.
 *
 * Unassessed recordings — too quiet, too noisy, clipped, no speech — are
 * excluded entirely rather than scored as zero. A refusal is evidence about
 * the room, not about the learner, and averaging it in would push someone
 * backwards for closing a door too loudly.
 */

export const PHONEMES: Phoneme[] = ['s', 'r', 'l', 'th']

/**
 * Weight given to the newest assessed attempt.
 *
 * 0.3 means roughly the last handful of attempts dominate: recent enough to
 * show improvement within a session, damped enough that one lucky or unlucky
 * recording does not swing the plan. It is the one tuning constant in this
 * file and it is stated rather than buried.
 */
export const MASTERY_ALPHA = 0.3

/**
 * Spread at which consistency reaches zero.
 *
 * A standard deviation of 0.25 across recent scores means readings roughly
 * half a scale apart, which is as inconsistent as this measure needs to
 * distinguish - beyond it, more spread tells us nothing new.
 */
const CONSISTENCY_SPREAD = 0.25

/** Net movement below this is noise, not direction. */
const TREND_DELTA = 0.06
/** With no net direction, spread this wide means variable rather than steady. */
const TREND_SPREAD = 0.28
/**
 * Scatter around the fitted line above which its direction is not believable.
 *
 * Measured: genuine ramps leave 0.00-0.02, oscillations leave 0.29-0.31.
 */
const TREND_NOISE = 0.12

/** A measurement, exactly as the acoustic stage reports it. */
export interface Measurement {
  phoneme: Phoneme
  /** 0–1. Null when the analyser declined to score. */
  similarity: number | null
  confidence: number | null
  assessed: boolean
}

function blankProfile(phoneme: Phoneme): PhonemeProfile {
  return {
    id: newId(),
    phoneme,
    masteryScore: 0,
    confidence: 0,
    attempts: 0,
    recentScores: [],
    trend: 'new',
    consistency: 0,
    currentStage: 'sound',
    repetitionCount: 0,
    contrastAccuracy: null,
    lastPracticed: null,
    updatedAt: now(),
  }
}

export async function getProfile(phoneme: Phoneme): Promise<PhonemeProfile> {
  const existing = await db.phonemeProfiles.where('phoneme').equals(phoneme).first()
  if (existing) return existing

  const created = blankProfile(phoneme)
  await db.phonemeProfiles.put(created)
  return created
}

/** Every phoneme, creating any that are missing. Always four rows. */
export async function getAllProfiles(): Promise<PhonemeProfile[]> {
  return Promise.all(PHONEMES.map(getProfile))
}

/** Weakest first — the natural order for building a syllabus. */
export async function getProfilesByNeed(): Promise<PhonemeProfile[]> {
  const profiles = await getAllProfiles()
  return [...profiles].sort((a, b) => {
    // Untested sounds come first: an unknown is a bigger gap than a low score.
    if (a.attempts === 0 && b.attempts > 0) return -1
    if (b.attempts === 0 && a.attempts > 0) return 1
    return a.masteryScore - b.masteryScore
  })
}

/**
 * How closely the recent scores agree with each other.
 *
 * Deliberately independent of how *good* they are: a learner scoring 0.4
 * every time is perfectly consistent and not yet accurate. Keeping the two
 * apart is what lets the policy require both before claiming mastery, rather
 * than letting a high average paper over wild variation.
 *
 * Zero below two scores. One point has no spread, and reporting perfect
 * consistency from it would be a claim made from nothing.
 */
export function deriveConsistency(scores: number[]): number {
  if (scores.length < 2) return 0
  const mean = scores.reduce((a, b) => a + b, 0) / scores.length
  const variance =
    scores.reduce((total, value) => total + (value - mean) ** 2, 0) / scores.length
  return round(Math.max(0, 1 - Math.sqrt(variance) / CONSISTENCY_SPREAD))
}

/**
 * Direction of travel over the recent window.
 *
 * A straight line is fitted to the recent scores; its total rise across the
 * window gives the direction, and the scatter left over says whether that
 * direction can be believed.
 *
 * Both halves of that matter, and each guards against a mistake the other
 * makes on its own:
 *
 *   - **Direction has to come first.** An earlier version checked spread
 *     first and called anything wide-ranging inconsistent, which misread
 *     0.4 -> 0.6 -> 0.8 as inconsistent. A learner who is steadily improving
 *     has a wide spread *by definition*, and that is the case this product
 *     exists to celebrate.
 *
 *   - **Direction has to be trusted second.** Comparing the older half of the
 *     window against the newer half - the version this replaces - is fooled
 *     by phase. Scores alternating 0.2 and 0.9 that happen to end on a high
 *     produce a half-mean difference of +0.23 and were reported as
 *     "improving". Somebody who cannot reproduce a sound twice running is not
 *     improving, and telling them so is worse than saying nothing.
 *
 * Measured across both kinds of series: a genuine ramp leaves a residual of
 * 0.00-0.02, an oscillation leaves 0.29-0.31. The line between them at 0.12
 * sits in a wide empty gap rather than on a knife edge.
 */
export function deriveTrend(scores: number[]): Trend {
  if (scores.length < 3) return 'new'

  const n = scores.length
  const meanX = (n - 1) / 2
  const meanY = scores.reduce((a, b) => a + b, 0) / n

  let covariance = 0
  let varianceX = 0
  for (let i = 0; i < n; i++) {
    covariance += (i - meanX) * (scores[i] - meanY)
    varianceX += (i - meanX) ** 2
  }
  const slope = varianceX === 0 ? 0 : covariance / varianceX
  const intercept = meanY - slope * meanX

  // Total modelled change from one end of the window to the other.
  const netChange = slope * (n - 1)
  const residual = Math.sqrt(
    scores.reduce((total, value, i) => total + (value - (slope * i + intercept)) ** 2, 0) / n,
  )

  // Too much scatter around the line for its direction to mean anything.
  if (residual >= TREND_NOISE) return 'inconsistent'

  if (netChange >= TREND_DELTA) return 'improving'
  if (netChange <= -TREND_DELTA) return 'declining'

  // No direction, and the line fits: wide range still means variable.
  const spread = Math.max(...scores) - Math.min(...scores)
  return spread >= TREND_SPREAD ? 'inconsistent' : 'stable'
}

/**
 * Fold one measurement into the learner model.
 *
 * The single entry point by which a profile changes on the strength of a
 * recording. Returns the updated profile so a caller can show what moved.
 */
export async function recordMeasurement(m: Measurement): Promise<PhonemeProfile> {
  const profile = await getProfile(m.phoneme)
  const timestamp = now()

  // An unassessed recording still counts as practice — it updates when they
  // last practised — but contributes nothing to mastery, confidence, or the
  // trend, because it contains no evidence about the sound.
  if (!m.assessed || m.similarity === null) {
    const held: PhonemeProfile = {
      ...profile,
      lastPracticed: timestamp,
      updatedAt: timestamp,
    }
    await db.phonemeProfiles.put(held)
    return held
  }

  const similarity = clamp01(m.similarity)
  const confidence = m.confidence === null ? profile.confidence : clamp01(m.confidence)

  const recentScores = [...profile.recentScores, similarity].slice(-RECENT_SCORES_KEPT)

  // First assessed attempt seeds the value rather than being averaged against
  // a zero that never represented anything. That does mean one good recording
  // can produce a high `masteryScore` — which is correct, it *is* the best
  // estimate from one reading. It is not mastery, and nothing treats it as
  // such: `assessMastery` requires `policy.minAttempts` before the word is
  // used at all. Score and verdict are separate for exactly this reason.
  const masteryScore =
    profile.attempts === 0
      ? similarity
      : profile.masteryScore + MASTERY_ALPHA * (similarity - profile.masteryScore)

  const meanConfidence =
    profile.attempts === 0
      ? confidence
      : profile.confidence + MASTERY_ALPHA * (confidence - profile.confidence)

  const updated: PhonemeProfile = {
    ...profile,
    masteryScore: round(masteryScore),
    confidence: round(meanConfidence),
    attempts: profile.attempts + 1,
    recentScores: recentScores.map(round),
    trend: deriveTrend(recentScores),
    consistency: deriveConsistency(recentScores),
    repetitionCount: profile.repetitionCount + 1,
    lastPracticed: timestamp,
    updatedAt: timestamp,
  }

  await db.phonemeProfiles.put(updated)
  return updated
}

/* ── Progression ──────────────────────────────────────────────────── */

/**
 * What the learner model currently believes about one sound.
 *
 * Reads the mode from settings so callers do not have to carry it, and so
 * switching to Accessibility Mode changes every judgement at once rather than
 * wherever someone remembered to check.
 */
export async function evaluate(phoneme: Phoneme): Promise<{
  profile: PhonemeProfile
  policy: LearnerPolicy
  mastery: MasteryVerdict
  stage: StageVerdict
}> {
  const [profile, mode] = await Promise.all([getProfile(phoneme), getLearningMode()])
  const policy = policyFor(mode)
  return {
    profile,
    policy,
    mastery: assessMastery(profile, policy),
    stage: assessStage(profile, policy),
  }
}

/**
 * Advance the stage if the evidence supports it, and report either way.
 *
 * Nothing here can move a learner backwards. A poor run leaves the stage
 * where it is, which is a pause rather than a demotion — being sent back a
 * rung for a bad day is punitive, and CLAUDE.md rules out punitive failure.
 */
export async function advanceIfReady(phoneme: Phoneme): Promise<{
  profile: PhonemeProfile
  advanced: boolean
  verdict: StageVerdict
}> {
  const { profile, stage } = await evaluate(phoneme)
  if (!stage.advance) return { profile, advanced: false, verdict: stage }

  const updated = await setStage(phoneme, stage.stage)
  return { profile: updated, advanced: true, verdict: stage }
}

/** Every sound the model currently considers mastered, under the active mode. */
export async function getMastered(): Promise<Phoneme[]> {
  const mode = await getLearningMode()
  const policy = policyFor(mode)
  const profiles = await getAllProfiles()
  return profiles
    .filter((profile) => assessMastery(profile, policy).mastered)
    .map((profile) => profile.phoneme)
}

/**
 * Move a phoneme to a different stage.
 *
 * `repetitionCount` resets, because it counts attempts *at the current
 * stage* — which is what accessibility mode's "more repetition before moving
 * on" is measured against.
 */
export async function setStage(
  phoneme: Phoneme,
  stage: SkillType,
): Promise<PhonemeProfile> {
  const profile = await getProfile(phoneme)
  if (!STAGE_ORDER.includes(stage)) {
    throw new Error(`Unknown stage "${stage}".`)
  }
  const updated: PhonemeProfile = {
    ...profile,
    currentStage: stage,
    repetitionCount: stage === profile.currentStage ? profile.repetitionCount : 0,
    updatedAt: now(),
  }
  await db.phonemeProfiles.put(updated)
  return updated
}

/** Recompute contrast accuracy for one phoneme from its contrast attempts. */
export async function setContrastAccuracy(
  phoneme: Phoneme,
  accuracy: number | null,
): Promise<PhonemeProfile> {
  const profile = await getProfile(phoneme)
  const updated: PhonemeProfile = {
    ...profile,
    contrastAccuracy: accuracy === null ? null : round(clamp01(accuracy)),
    updatedAt: now(),
  }
  await db.phonemeProfiles.put(updated)
  return updated
}

function clamp01(value: number): number {
  return Math.max(0, Math.min(1, value))
}

function round(value: number): number {
  return Math.round(value * 1e4) / 1e4
}
