import { SETTINGS_ID, db, newId, now } from './schema.ts'
import type { LearningMode, SelfLevel, Settings } from './schema.ts'

/**
 * Settings: one row, created on first read.
 *
 * `getSettings()` never returns null. A learner opening the app for the first
 * time gets working defaults rather than a null check in every caller — which
 * is what "works immediately without registration" means in practice.
 */

export const DEFAULT_SETTINGS: Omit<Settings, 'id' | 'createdAt' | 'updatedAt'> = {
  nativeLanguage: 'en',
  targetLanguage: 'en',
  level: 'beginner',
  learningGoal: '',
  // Standard is the default. Accessibility is offered, never assigned — the
  // learner chooses it, and can switch back at any time.
  learningMode: 'standard',
}

export async function getSettings(): Promise<Settings> {
  const existing = await db.settings.get(SETTINGS_ID)
  if (existing) return existing

  // One timestamp for both fields. Two `now()` calls can straddle a
  // millisecond boundary and produce different strings, which used to make a
  // brand-new profile look like it had been edited.
  const timestamp = now()
  const created: Settings = {
    id: SETTINGS_ID,
    ...DEFAULT_SETTINGS,
    createdAt: timestamp,
    updatedAt: timestamp,
  }
  // `put` rather than `add`: two components mounting at once would both miss
  // the read above, and the second `add` would throw on the unique key.
  await db.settings.put(created)
  return created
}

export async function updateSettings(
  patch: Partial<Omit<Settings, 'id' | 'createdAt'>>,
): Promise<Settings> {
  const current = await getSettings()
  const next: Settings = { ...current, ...patch, id: SETTINGS_ID, updatedAt: now() }
  await db.settings.put(next)
  return next
}

export async function setLearningMode(mode: LearningMode): Promise<Settings> {
  return updateSettings({ learningMode: mode })
}

export async function setLanguages(
  nativeLanguage: string,
  targetLanguage: string,
): Promise<Settings> {
  return updateSettings({ nativeLanguage, targetLanguage })
}

export async function completeOnboarding(input: {
  nativeLanguage: string
  targetLanguage: string
  level: SelfLevel
  learningGoal: string
  learningMode: LearningMode
}): Promise<Settings> {
  return updateSettings(input)
}

/**
 * True once the learner has been through onboarding.
 *
 * Keyed on `learningGoal`, which onboarding always sets and the defaults
 * leave empty. An earlier version compared `updatedAt` against `createdAt`,
 * which was wrong twice over: the two were generated by separate `now()`
 * calls that can straddle a millisecond, and any later settings change would
 * have made an un-onboarded profile look onboarded. Measured: roughly 1 in
 * 1200 fresh profiles reported the wrong answer.
 */
export async function hasOnboarded(): Promise<boolean> {
  const settings = await db.settings.get(SETTINGS_ID)
  return Boolean(settings?.learningGoal)
}

/** Convenience for the many places that only need the mode. */
export async function getLearningMode(): Promise<LearningMode> {
  return (await getSettings()).learningMode
}

/** Used when seeding a fresh database; not part of the normal flow. */
export function freshSettings(): Settings {
  const timestamp = now()
  return {
    id: SETTINGS_ID,
    ...DEFAULT_SETTINGS,
    createdAt: timestamp,
    updatedAt: timestamp,
  }
}

export { newId }
