"""
Practice material for a stage — generated by Groq, bounded by code.

The division of labour here is the point of the whole feature:

    the language model writes the exercise
    the microphone decides whether it was passed

Groq is asked for words, phrases and sentences suited to the learner's
current stage. It is never asked how well anything was pronounced, it never
sees a recording, and nothing it returns can reach the progression policy.
Three separate mechanisms enforce that rather than one:

  1. `StageMaterial` sets `extra="forbid"`, so a response carrying a score,
     a rating, a percentage or any other unexpected field fails validation
     outright instead of being quietly ignored.
  2. Every field is a string. There is no numeric field for a model to fill
     in even if it wanted to.
  3. `generate()` returns material only. The caller measures the recording
     separately and never passes this object to `policy.decide()`.

Beyond that, generated material is *verified before use*: the target sound
has to actually be at the start of the first word, checked against the
spelling in code. A model that returns "banana" for an /s/ stage is rejected
and the deterministic bank is used instead. Plausible-looking material that
does not contain the sound being practised would corrupt the measurement
downstream, which is a subtler failure than a wrong score and a worse one.

**The fallback bank is not a degraded mode.** It is hand-written, covers
every stage of every sound, and is what runs with no API key, no network, a
timeout, or a rejected response. The demo never depends on a network call.
"""

from __future__ import annotations

import json
import logging
import random
from typing import Any

import httpx
from pydantic import BaseModel, ConfigDict, Field, ValidationError

from ..config import Settings
from ..languages import DEFAULT_NATIVE, language, normalise_native
from .stages import Stage, stage as stage_at

log = logging.getLogger(__name__)

#: Every journey item's target sound is word-initial, and `Material.position`
#: is always "onset" as a result. Practising a sound in the middle or at the
#: end of a word is genuinely valuable — "yellow" for /l/, "bath" for /th/ —
#: but the segmenter locates a medial approximant far less reliably than an
#: initial one, and a journey that advanced people on an unreliable
#: measurement would be worse than one that covers less ground. The older
#: /api/attempts prompt bank does carry coda and medial positions; the
#: journey will follow once alignment lands (ARCHITECTURE.md §3).
#:
#: Spelling prefixes that reliably begin with each target sound. Used to
#: verify generated material. Conservative on purpose — "city" does start
#: with /s/, but accepting soft-c would also accept "chair", and a missed
#: good word costs nothing while a wrong one corrupts a measurement.
_ONSET_SPELLINGS: dict[str, tuple[str, ...]] = {
    "s": ("s",),
    "th": ("th",),
    "r": ("r", "wr"),
    "l": ("l",),
}
#: Prefixes that look right but are a different sound entirely.
_ONSET_EXCLUSIONS: dict[str, tuple[str, ...]] = {
    "s": ("sh",),
    # See _VOICED_TH below: "th" cannot be excluded by prefix, because the
    # voiced and voiceless spellings are the same.
    "th": (),
    "r": (),
    "l": (),
}

#: Word-initial voiced TH. A closed class, and every one of them is a trap.
#:
#: English spells /theta/ and /eth/ identically. The reference corpus for "th"
#: is entirely voiceless - theme, thick, thin, thing, think, thumb - so a
#: prompt beginning "the" or "this" would be measured against a profile for a
#: different sound, and a learner producing it perfectly would be marked down
#: for it. Observed: a generated /th/ phrase came back as "the thick thrum"
#: and a sentence as "This thing is theirs", both of which begin voiced.
#:
#: Matched whole-word, not by prefix, because "theme" and "therapy" are
#: voiceless and would be caught by any prefix that catches "the".
_VOICED_TH: frozenset[str] = frozenset(
    {
        "the", "this", "that", "these", "those",
        "they", "them", "their", "theirs", "themselves",
        "then", "than", "though", "thus", "thence",
        "thee", "thy", "thine", "thou", "tho",
    }
)

#: "there", "therefore", "thereby"... all voiced. No voiceless word starts
#: "there" - "therapy" and "therapeutic" start "thera".
_VOICED_TH_PREFIX = "there"


class StageMaterial(BaseModel):
    """
    One thing to practise. Strings only, and no field a score could occupy.

    `extra="forbid"` is load-bearing: it is what turns "the model added a
    `score` field" from a silent no-op into a validation error.
    """

    model_config = ConfigDict(extra="forbid")

    #: What the learner says. Exactly what is measured.
    text: str = Field(min_length=1, max_length=160)
    #: A friendlier rendering for stages where `text` is not a word —
    #: "ssss" for a held /s/, say. Display only.
    display: str | None = Field(default=None, max_length=40)
    #: A minimal-pair counterpart, shown for contrast. Never practised, and
    #: never measured.
    contrast: str | None = Field(default=None, max_length=40)
    #: One short articulation tip.
    cue: str = Field(min_length=1, max_length=200)


class Material(BaseModel):
    """What the endpoint returns."""

    sound: str
    stage: int
    stage_key: str
    item: StageMaterial
    #: "llm" or "fallback". Always shown in the UI — a learner should be able
    #: to see where their exercise came from.
    source: str
    #: Where in the utterance the target sound is measured.
    position: str = "onset"
    #: True at stages 5-7, where only the first occurrence is assessed.
    first_occurrence_only: bool = False
    #: The learner's first language at the time this was generated, and the
    #: language being practised. Reported so the UI can show what the
    #: material was personalized for — and so it is visible that the target
    #: is always English.
    native_language: str = DEFAULT_NATIVE
    target_language: str = "en"


# ── The deterministic bank ───────────────────────────────────────────
#
# Several options per stage so that a "hold, with different material"
# decision has something different to offer.

_BANK: dict[str, dict[str, list[StageMaterial]]] = {
    "s": {
        "isolated": [StageMaterial(text="s", display="sssss", cue="Teeth almost closed, tongue tip behind the top teeth, and a long thin stream of air.")],
        "syllable": [
            StageMaterial(text="sah", cue="Hold the hiss, then open straight into the vowel without stopping."),
            StageMaterial(text="see", cue="Keep the hiss going right up to the vowel."),
            StageMaterial(text="so", cue="Start the air before you round your lips."),
        ],
        "word_simple": [
            StageMaterial(text="sun", contrast="thumb", cue="Start the word with the hiss already going."),
            StageMaterial(text="sock", cue="Keep the tongue tip up behind the teeth."),
            StageMaterial(text="sing", contrast="thing", cue="A long /s/, then the rest of the word."),
        ],
        "word_complex": [
            StageMaterial(text="seven", cue="Two syllables — keep the /s/ as clear as it was on its own."),
            StageMaterial(text="silver", cue="Do not let the /s/ shorten just because the word is longer."),
            StageMaterial(text="sunset", cue="Two /s/ sounds. Give the first one its full length."),
        ],
        "phrase": [
            StageMaterial(text="silver snake", cue="One breath, no pause between the words."),
            StageMaterial(text="seven socks", cue="Keep both /s/ sounds equally long."),
        ],
        "sentence": [
            StageMaterial(text="Sam sees seven silver socks.", cue="Natural pace. Do not slow down for the /s/ sounds."),
            StageMaterial(text="Sunset came slowly today.", cue="Let the opening /s/ start cleanly."),
        ],
        "conversation": [
            StageMaterial(text="Something I like doing is", display="Something I like doing is…", cue="Finish the sentence in your own words. Speak normally."),
            StageMaterial(text="Summer is my favourite because", display="Summer is my favourite because…", cue="Carry on in your own words, at a natural pace."),
        ],
    },
    "r": {
        "isolated": [StageMaterial(text="r", display="rrrrr", cue="Lips relaxed, not rounded. Pull the back of the tongue up and back.")],
        "syllable": [
            StageMaterial(text="rah", cue="Hold the /r/ shape, then release into the vowel."),
            StageMaterial(text="ree", cue="Keep the lips still — the tongue does the work."),
            StageMaterial(text="roo", cue="Round the lips only after the /r/ has started."),
        ],
        "word_simple": [
            StageMaterial(text="red", contrast="wed", cue="Lips relaxed. If they push forward, it becomes /w/."),
            StageMaterial(text="ring", contrast="wing", cue="Start with the tongue already back."),
            StageMaterial(text="road", cue="Hold the /r/ a moment before the vowel."),
        ],
        "word_complex": [
            StageMaterial(text="rabbit", cue="Two syllables. Keep the opening /r/ full length."),
            StageMaterial(text="rainbow", cue="Do not let the /r/ soften into /w/."),
            StageMaterial(text="railroad", cue="Two /r/ sounds — give both the same shape."),
        ],
        "phrase": [
            StageMaterial(text="red rabbit", cue="One breath, both /r/ sounds clear."),
            StageMaterial(text="round rock", cue="Keep the lips relaxed through both words."),
        ],
        "sentence": [
            StageMaterial(text="Red rabbits run round the rock.", cue="Natural pace."),
            StageMaterial(text="Rain fell on the road.", cue="Let the /r/ start the word cleanly."),
        ],
        "conversation": [
            StageMaterial(text="Really good days are when", display="Really good days are when…", cue="Finish the sentence in your own words. Speak normally."),
            StageMaterial(text="Rain makes me want to", display="Rain makes me want to…", cue="Carry on in your own words, at a natural pace."),
        ],
    },
    "l": {
        "isolated": [StageMaterial(text="l", display="lllll", cue="Tongue tip firmly on the ridge behind your top teeth. Air flows around the sides.")],
        "syllable": [
            StageMaterial(text="lah", cue="Touch the ridge first, then drop the tongue for the vowel."),
            StageMaterial(text="lee", cue="Feel the contact before any sound comes out."),
            StageMaterial(text="loo", cue="Contact first, rounding second."),
        ],
        "word_simple": [
            StageMaterial(text="light", contrast="right", cue="Tongue tip touches — it should not curl back."),
            StageMaterial(text="leaf", cue="Hold the contact for a moment before the vowel."),
            StageMaterial(text="look", contrast="wook", cue="Tip up. If the lips round instead, it becomes /w/."),
        ],
        "word_complex": [
            StageMaterial(text="lemon", cue="Two syllables. Keep the opening contact firm."),
            StageMaterial(text="lemonade", cue="Three syllables. The opening /l/ still needs full contact."),
            StageMaterial(text="lollipop", cue="Two /l/ sounds. Touch the ridge for both."),
        ],
        "phrase": [
            StageMaterial(text="little lemon", cue="One breath, tongue tip touching on each /l/."),
            StageMaterial(text="long yellow leaf", cue="Three /l/ sounds — do not rush them."),
        ],
        "sentence": [
            StageMaterial(text="Lily likes little lemon leaves.", cue="Natural pace."),
            StageMaterial(text="Lights were low last night.", cue="Clear contact at the start of each /l/."),
        ],
        "conversation": [
            StageMaterial(text="Last weekend I", display="Last weekend I…", cue="Finish the sentence in your own words. Speak normally."),
            StageMaterial(text="Lunch is best when", display="Lunch is best when…", cue="Carry on in your own words, at a natural pace."),
        ],
    },
    "th": {
        "isolated": [StageMaterial(text="th", display="thhhh", cue="Tongue tip just past your top teeth, and blow gently. It is a quiet sound.")],
        "syllable": [
            # Nonsense syllables on purpose, and none of them a real word:
            # "thee" and "tho" read as the voiced pronoun and as "though", so
            # a learner would say the voiced sound while being measured
            # against the voiceless reference the corpus is built from.
            StageMaterial(text="thah", cue="Let the tongue slip back in as the vowel starts."),
            StageMaterial(text="thoo", cue="Gentle air — do not push."),
            StageMaterial(text="thuh", cue="Keep the tongue forward for the whole /th/."),
        ],
        "word_simple": [
            StageMaterial(text="think", contrast="sink", cue="Tongue between the teeth, not behind them."),
            StageMaterial(text="thumb", cue="Soft airflow. It should be quieter than /s/."),
            StageMaterial(text="thin", contrast="fin", cue="Tongue, not lip. Keep the bottom lip away from your teeth."),
        ],
        "word_complex": [
            StageMaterial(text="thunder", cue="Two syllables. Do not let the /th/ vanish."),
            StageMaterial(text="thirty", cue="A /th/ then an /r/ — take them one at a time."),
            StageMaterial(text="thankful", cue="Keep the opening /th/ gentle and forward."),
        ],
        "phrase": [
            StageMaterial(text="three things", cue="One breath, both /th/ sounds forward."),
            StageMaterial(text="thick thread", cue="Gentle air on both."),
        ],
        "sentence": [
            StageMaterial(text="Three thin threads tangled.", cue="Natural pace, tongue forward each time."),
            StageMaterial(text="Thursday is the third day I like.", cue="Let each /th/ stay soft."),
        ],
        "conversation": [
            StageMaterial(text="Thinking about the weekend makes me", display="Thinking about the weekend makes me…", cue="Finish the sentence in your own words. Speak normally."),
            StageMaterial(text="Things I enjoy most are", display="Things I enjoy most are…", cue="Carry on in your own words, at a natural pace."),
        ],
    },
}


def _first_word(text: str) -> str:
    cleaned = "".join(c for c in text.lower() if c.isalpha() or c.isspace()).strip()
    return cleaned.split(" ")[0] if cleaned else ""


def starts_with_target(text: str, sound: str) -> bool:
    """
    Does the first word actually begin with the target sound?

    Spelling-based and deliberately strict. This is the guard that stops
    generated material from silently breaking the measurement: the acoustic
    stage looks for the target at the start of the utterance, so material
    whose first word does not begin with it would be scored against
    something that is not there.
    """
    word = _first_word(text)
    if not word:
        return False
    if sound == "th" and (word in _VOICED_TH or word.startswith(_VOICED_TH_PREFIX)):
        return False
    # `text` is already a bare sound at the isolated stage.
    if word == sound or (sound == "th" and word.startswith("th")):
        return True
    if any(word.startswith(bad) for bad in _ONSET_EXCLUSIONS.get(sound, ())):
        return False
    return any(word.startswith(good) for good in _ONSET_SPELLINGS.get(sound, ()))


def fallback(
    sound: str, stage_index: int, *, avoid: str | None = None, native: str = DEFAULT_NATIVE
) -> Material:
    """
    Deterministic material. Always available, always valid.

    The bank itself is not translated or varied by first language. The words
    that isolate an English /s/ are the same words whoever is practising, and
    producing a separate bank per language would mean maintaining several
    sets of English words with no reason for them to differ. What the first
    language changes is the *bridge* shown alongside (see `app/languages.py`)
    and the context given to the generator below.
    """
    current = stage_at(stage_index)
    options = _BANK[sound][current.key]
    # `avoid` implements "hold with varied material": pick something the
    # learner did not just do, when there is anything else to pick.
    choices = [o for o in options if o.text != avoid] or options
    return _wrap(sound, current, random.choice(choices), "fallback", native)


def _wrap(
    sound: str, current: Stage, item: StageMaterial, source: str, native: str = DEFAULT_NATIVE
) -> Material:
    return Material(
        sound=sound,
        stage=current.index,
        stage_key=current.key,
        item=item,
        source=source,
        position="onset",
        first_occurrence_only=current.index >= 5,
        native_language=normalise_native(native),
        target_language="en",
    )


_SYSTEM = (
    "You write very short pronunciation practice material for a children's "
    "speech-learning app. You never assess, score, rate or diagnose anything: "
    "a separate acoustic system measures the recording and owns every "
    "judgement about performance. Never mention disorders, diagnosis, "
    "therapy or clinical terms. "
    # The learner's first language is given as context so that examples can be
    # familiar. It is not licence to explain their pronunciation with it.
    "When you are told a learner's first language, use it only to choose "
    "words and examples that will be familiar. Never say or imply that their "
    "first language causes, explains, or predicts any pronunciation pattern, "
    "and never describe any language as lacking, missing, or deficient in a "
    "sound. Reply with JSON only."
)


def _user_prompt(
    sound: str, current: Stage, avoid: str | None, native: str = DEFAULT_NATIVE
) -> str:
    shape = {
        "isolated": "the single sound held on its own",
        "syllable": "the sound joined to one vowel, as a nonsense syllable",
        "word": "one short, common, single-syllable word",
        "word_complex": "one common word of two or three syllables",
        "phrase": "a two or three word phrase",
        "sentence": "one short sentence of six to ten words",
        "conversation": "an unfinished sentence opener of three to five words for "
        "the learner to complete in their own words",
    }[current.material]

    rules = [
        f"Target sound: /{sound}/.",
        f"Produce {shape}.",
        "The FIRST word must begin with the target sound.",
        "Use real English words a seven-year-old knows.",
        "cue: one sentence about where the tongue or lips go. No praise, no assessment.",
        "contrast: a minimal-pair word differing only in the target sound, or null.",
        'display: only for a bare sound, e.g. "sssss". Otherwise null.',
        "Return exactly: {\"text\": str, \"display\": str|null, "
        '"contrast": str|null, "cue": str}',
        "Do not include any other field. Do not include any number, score, "
        "rating or percentage anywhere in the response.",
    ]
    resolved = normalise_native(native)
    if resolved != "en":
        # Context, deliberately narrow: familiarity of examples, nothing else.
        # The target is always English — the sound being measured is an
        # English one — and saying so keeps the model from drifting into
        # generating practice material in the learner's first language.
        rules.append(
            f"The learner's first language is {language(resolved).name} and "
            "they are learning English. The word must still be an English "
            "word. Where a natural choice exists, prefer everyday words that "
            "would be familiar to a learner in that cultural context. Do not "
            "explain their pronunciation by reference to their first language."
        )
    if avoid:
        rules.append(f'Do not use "{avoid}" — the learner has just practised it.')
    return "\n".join(rules)


def _parse(content: str) -> StageMaterial:
    text = content.strip().removeprefix("```json").removeprefix("```").removesuffix("```")
    payload = json.loads(text)
    if not isinstance(payload, dict):
        raise ValueError("generator returned a non-object")
    # Validation, not sanitisation. A response carrying an unexpected field
    # is rejected rather than cleaned up, so the guard cannot be defeated by
    # a field name nobody thought of.
    return StageMaterial.model_validate(payload)


async def generate(
    sound: str,
    stage_index: int,
    settings: Settings,
    *,
    avoid: str | None = None,
    native: str = DEFAULT_NATIVE,
    client: httpx.AsyncClient | None = None,
) -> Material:
    """
    Ask Groq for material, and fall back to the bank on any problem at all.

    Never raises. A failed generation is not an error the learner should see —
    it is a reason to use a hand-written exercise that is just as good.
    """
    current = stage_at(stage_index)

    # The isolated stage has exactly one correct answer and nothing to vary.
    # Spending an API call to be told to hold an /s/ would be waste.
    if current.material == "isolated":
        return fallback(sound, stage_index, avoid=avoid, native=native)

    keys = settings.groq_api_key_pool
    if not keys:
        return fallback(sound, stage_index, avoid=avoid, native=native)

    payload: dict[str, Any] = {
        "model": settings.groq_chat_model,
        "temperature": 0.7,
        # 1200, not the ~300 the output actually needs. Reasoning models on
        # Groq (the gpt-oss family) spend tokens thinking before they emit
        # anything, and that budget is shared with the response. At 300 the
        # longer stages returned HTTP 400 json_validate_failed with an empty
        # `failed_generation` — the model had produced no JSON at all before
        # running out. The wasted headroom costs nothing when unused.
        "max_tokens": 1200,
        "response_format": {"type": "json_object"},
        "messages": [
            {"role": "system", "content": _SYSTEM},
            {"role": "user", "content": _user_prompt(sound, current, avoid, native)},
        ],
    }
    url = f"{settings.groq_base_url.rstrip('/')}/chat/completions"

    owned = client is None
    http = client or httpx.AsyncClient(timeout=settings.llm_timeout_s)
    try:
        # One attempt per key, no retry within a key: the bank is right there,
        # and a learner waiting on a second timeout is worse than a
        # hand-written word.
        for key in keys:
            try:
                response = await http.post(
                    url, headers={"Authorization": f"Bearer {key}"}, json=payload
                )
                response.raise_for_status()
                item = _parse(response.json()["choices"][0]["message"]["content"])
            except (httpx.HTTPError, KeyError, IndexError, TypeError, ValueError, ValidationError) as exc:
                log.info("material generation failed on one key: %s", type(exc).__name__)
                continue

            if not starts_with_target(item.text, sound):
                log.info(
                    "generated %r does not start with /%s/ — using the bank", item.text, sound
                )
                continue

            return _wrap(sound, current, item, "llm", native)
    finally:
        if owned:
            await http.aclose()

    return fallback(sound, stage_index, avoid=avoid, native=native)
