"""
The advancement policy — when a learner moves, and which way.

This module is deliberately a pure function of past outcomes. It takes no
audio, calls no model, and touches no I/O, which is what makes the whole
progression testable: `decide()` can be driven through any sequence of
attempts in a unit test and the result is exact.

**Where the decision comes from matters more than the rules themselves.**
Every outcome fed in here is derived from `app/acoustic/` — a measurement of
the recording. The material a learner practises is generated by a language
model, but nothing a language model produces ever reaches this function. The
generator writes the exercise; the microphone decides whether it was passed.

The four rules, in the order they are evaluated:

    1. the last attempt could not be assessed  -> hint, and retry the stage
    2. two decisive successes in a row         -> advance
    3. two decisive failures in a row          -> retreat
    4. successes and failures mixed            -> hold, with new material

Rule 1 comes first because an unassessable attempt is not evidence about the
learner at all — it is evidence about the recording. Counting it as a failure
would push someone backwards for sitting in a noisy room, so unclear attempts
are excluded from the streaks entirely rather than merely ignored at the top.
"""

from __future__ import annotations

from dataclasses import dataclass

from ..acoustic.scoring import CLOSE_SIMILARITY, ON_TARGET_SIMILARITY
from .stages import FIRST_STAGE, LAST_STAGE

# ── Outcomes ─────────────────────────────────────────────────────────
#: Measured as the target sound, clearly.
PASS = "pass"
#: Measured as the target sound, but imprecisely. Neither a success nor a
#: failure: it is progress worth repeating, not worth advancing on.
CLOSE = "close"
#: Measured as a different sound, or too far from the target to count.
FAIL = "fail"
#: The analysis declined to name a sound. Says nothing about the learner.
UNCLEAR = "unclear"

# ── Decisions ────────────────────────────────────────────────────────
ADVANCE = "advance"
RETREAT = "retreat"
HOLD = "hold"
HINT = "hint"

#: How many decisive attempts in a row are needed to move a stage. Two is a
#: deliberate choice for a practice tool: three makes progress feel stuck on
#: a five-minute demo, one lets a single lucky attempt carry someone into
#: material they cannot do.
STREAK = 2

#: How far back rule 4 looks for inconsistency.
WINDOW = 3


@dataclass(frozen=True)
class Decision:
    action: str
    from_stage: int
    to_stage: int
    #: Learner-facing sentence explaining the move.
    reason: str
    #: True when the material for the next attempt should deliberately differ
    #: from what was just practised.
    vary_material: bool = False
    #: True when the UI should show a hint before the learner records again.
    show_hint: bool = False

    @property
    def moved(self) -> bool:
        return self.to_stage != self.from_stage


def outcome_of(
    *, assessed: bool, estimated_match: str | None, target: str, similarity: float
) -> str:
    """
    Classify one attempt from its acoustic result.

    The thresholds are the same constants the analysis stage uses for its own
    feedback wording, imported rather than repeated, so the journey can never
    call something a pass that the results screen called imprecise.
    """
    if not assessed or estimated_match is None:
        return UNCLEAR
    if estimated_match != target:
        return FAIL
    if similarity >= ON_TARGET_SIMILARITY:
        return PASS
    if similarity >= CLOSE_SIMILARITY:
        return CLOSE
    return FAIL


def decide(current_stage: int, outcomes: list[str]) -> Decision:
    """
    Decide what happens next.

    Args:
        current_stage: the stage the learner is on now.
        outcomes: outcomes at *this* stage, oldest first. Attempts from
            earlier stages are not included — a failure at stage 5 says
            nothing about stage 3, and carrying it over would make retreating
            feel like a trap.
    """
    if not outcomes:
        return Decision(
            HOLD, current_stage, current_stage,
            "Record your first attempt at this stage.",
        )

    if outcomes[-1] == UNCLEAR:
        return Decision(
            HINT, current_stage, current_stage,
            "That recording could not be measured, so the stage stays the "
            "same. Here is something to try before the next one.",
            show_hint=True,
        )

    # Unclear attempts are dropped entirely, not treated as neutral entries
    # that break a streak. A learner who passes, hits background noise, then
    # passes again has succeeded twice in a row.
    decisive = [o for o in outcomes if o in (PASS, CLOSE, FAIL)]
    if not decisive:
        return Decision(
            HOLD, current_stage, current_stage,
            "Not enough measurable attempts yet. Try this one again.",
        )

    recent = decisive[-STREAK:]

    if len(recent) == STREAK and all(o == PASS for o in recent):
        if current_stage >= LAST_STAGE:
            return Decision(
                HOLD, current_stage, current_stage,
                "You are at the final stage of this journey. Keep practising "
                "with new material.",
                vary_material=True,
            )
        return Decision(
            ADVANCE, current_stage, current_stage + 1,
            "Two clear attempts in a row — moving up to something harder.",
            vary_material=True,
        )

    if len(recent) == STREAK and all(o == FAIL for o in recent):
        if current_stage <= FIRST_STAGE:
            return Decision(
                HOLD, current_stage, current_stage,
                "This is the simplest stage, so we will stay here and keep "
                "working on it.",
                vary_material=True,
            )
        return Decision(
            RETREAT, current_stage, current_stage - 1,
            "Stepping back to something simpler to rebuild the sound.",
            vary_material=True,
        )

    window = decisive[-WINDOW:]
    if PASS in window and FAIL in window:
        return Decision(
            HOLD, current_stage, current_stage,
            "Results are mixed at this stage — staying here with different "
            "words to steady it.",
            vary_material=True,
        )

    return Decision(
        HOLD, current_stage, current_stage,
        "Close. One more clear attempt at this stage and you move up.",
    )
